### PR TITLE
Update FreeDesktop runtime to 22.08

### LINKED ISSUE #13: runtime org.freedesktop.Platform branch 20.08 is end-of-life
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### LINKED ISSUE #14: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### LINKED ISSUE #15: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### PR DESCRIPTION
**Pull request by Calinou**
Tested locally, the game runs correctly.

- This closes https://github.com/flathub/com.teeworlds.Teeworlds/issues/13, closes https://github.com/flathub/com.teeworlds.Teeworlds/issues/14 and closes https://github.com/flathub/com.teeworlds.Teeworlds/issues/15.

### CODE REVIEW

**Comment by Calinou** [comment]
I just realized this does the same thing as https://github.com/flathub/com.teeworlds.Teeworlds/pull/12, but this one has autoclosing issue references. :no_mouth: 

Pick whichever you want.

**Comment by sonnyp** [comment]
Can someone merge this? :pray:

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Seems to run, merging . Thanks!

I'll update it to 23.08 later or if you want to help, please do :)

**Pull request merged**
